---

- include: common.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: postgresql
    state: started
    enabled: yes

- include: configure.yml

# Configure the master node
- include: master.yml
  when: postgresql_master

- block:
  - name: setup ssh
    include: repmgr_ssh.yml
  - name: configure repmgr
    include: repmgr_config.yml
  - name: bootstrap repmgr nodes
    include: repmgr_bootstrap.yml
  when:
    groups['postgresql'] | length > 1
