---

- include: common.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: postgresql
    state: started
    enabled: yes

- include: configure.yml

# Configure the master node
- include: master.yml
  when: postgresql_master

- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- block:
  - name: setup ssh
    include: repmgr_ssh.yml
    tags: repmgr-ssh

  - name: configure repmgr
    include: repmgr_config.yml
    tags: repmgr-config

  - name: bootstrap repmgr nodes
    include: repmgr_bootstrap.yml
    tags: repmgr-bootstrap

  when: groups['postgresql'] | length > 1
  tags: repmgr

- include: pgbouncer.yml
  when: (groups['postgresql'] | length > 1) and (postgresql_master | bool)
  tags: pgbouncer
