---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: jessie64
      box: debian/jessie64
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: molecule-ruby
      ansible_groups:
        - ruby
verifier:
  name: serverspec
