---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install some stuff the app needs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - 'libv8-3.14.5'
    - 'nodejs'
    - 'build-essential'
    - 'qt5-default'
    - 'libqt5webkit5-dev'
    - 'libpq5'
    - 'libpq-dev'

- block:
    - include: clean.yml
      tags: clean-webapp

    - include: install.yml
      tags: install-webapp

    - include: bundle.yml
      tags: bundle

    - include: systemd.yml
      tags: systemd

    - name: start mpal-web
      service:
        name: mpal-web
        state: started

    - name: start mpal-worker
      service:
        name: mpal-worker
        state: started
  when: package is defined
