---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install some stuff the app needs and I do not know why
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - 'libv8-3.14.5'
    - 'nodejs'
    - 'build-essential'
    - 'qt5-default'
    - 'libqt5webkit5-dev'
    - 'libpq5'
    - 'libpq-dev'

- block:
    - name: Unpack the app
      unarchive:
        src: "{{ package }}.tar.bz2"
        dest: /home/mpal

    - include: bundle.yml
    - include: systemd.yml

    - notify: Start MPAL
  when: package is defined
