---
##########
# repos
debian_backports_repo:

###############
# keepalived
keepalived_vip: '10.67.73.100'
keepalived_configurations:
  - keepalived_instance: '1'
    keepalived_interface: 'eth0'
    keepalived_priority: '150'

############
# haproxy
haproxy_frontend_name: front-test-haproxy
haproxy_frontend_ip: "{{ keepalived_vip }}"
haproxy_frontend_port: 80
haproxy_backend_name: back-mpal-test
haproxy_backend_servers:
  - name: 'be-demat-webapp1'
    ip: '10.67.73.19'
    port: '3000'
  - name: 'be-demat-webapp2'
    ip: '10.67.73.20'
    port: '3000'

haproxy_stats_login: mpal
haproxy_stats_password: mpal

##########
# redis
redis_host_port: 6379
redis_password: foobar
redis_master_conf:
  ip: 10.67.73.22
  password: '{{ redis_password }}'

#############
# postgres
postgresql_master_ip: 10.67.73.21
postgresql_host_port: 5432
postgresql_mpal_username: mpal
postgresql_mpal_password: mpal
postgresql_mpal_attr_flags: SUPERUSER,LOGIN,CREATEROLE,CREATEDB,REPLICATION
postgresql_webapp_cidr: 10.67.73.0/24

############
# webapps
webapp_dot_env_conf: test
webapp_rails_env: production
webapp_postgresql_master: "{{ postgresql_master_ip }}"
