---
- hosts: all
  roles:
    - role: keepalived
      keepalived_vip: '10.0.1.66'
      keepalived_configurations:
        - keepalived_instance: '1'
          keepalived_interface: 'eth0'
          keepalived_priority: '150'
