---

- name: Install some stuff the app needs and I do not know why
  apt:
    name: “{{ item }}"
    state: present
  with_items:
    - nodejs
    - build-essential
    - qt5-default
    - libqt5webkit5-dev
    - libpq5

- name: Install ruby and rubygems
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby-full
    - rubygems-integration
