---
##########
# repos
debian_backports_repo:

###############
# keepalived
keepalived_vip: '10.66.73.100'
keepalived_cidr: '24'
keepalived_configurations:
  - keepalived_instance: '1'
    keepalived_interface: 'eth0'
    keepalived_priority: '150'

############
# haproxy
haproxy_frontend_name: front-test-haproxy
haproxy_frontend_ip: "*"
haproxy_ssl_pem_file: mpal-web-prod.pem
haproxy_frontend_vhost: monprojet.anah.gouv.fr

haproxy_backend_name: back-mpal-test
haproxy_backend_servers:
  - name: 'be-demat-webapp1'
    ip: ''
    port: '3000'
  - name: 'be-demat-webapp2'
    ip: ''
    port: '3000'

haproxy_stats_login: mpal
haproxy_stats_password: mpal

##########
# redis
redis_host_port: 6379
redis_password: foobar
redis_master_conf:
  ip: 10.66.73.16
  password: "{{ redis_password }}"
redis_slaves_conf:
  - ip: 10.66.73.15
    password: "{{ redis_password }}"
    master_password: "{{ redis_password }}"

#############
# postgres
postgresql_master_ip: 10.66.73.15
postgresql_host_port: 5432
postgresql_standby_ip: 10.66.73.16
postgresql_mpal_username: "{{ vaulted.postgres_username }}"
postgresql_mpal_password: "{{ vaulted.postgres_password }}"
postgresql_mpal_attr_flags: SUPERUSER,LOGIN,CREATEROLE,CREATEDB,REPLICATION
postgresql_cidr: 10.66.73.0/24
postgresql_webapp_cidr: "{{ postgresql_cidr }}"
postgresql_backend_cidr: "{{ postgresql_cidr }}"

###########
# repmgr
repmgr_cluster_name: production_cluster

############
# webapps
webapp_api_particulier_domain: particulier.api.gouv.fr
webapp_clamav_enabled: 'true'
webapp_clavis_url: https://clavis.anah.fr/clavis/
webapp_demo: 'false'
webapp_enabled_departements: 88
webapp_display_demo_credentials: 'false'
webapp_domain: monprojet.anah.gouv.fr
webapp_env_name: PROD
webapp_opal_api_base_uri: https://opal.anah.gouv.fr/
webapp_payments_enabled: 'true'
webapp_rails_env: production
webapp_rod_api_base_uri: https://rod-dev.anah.fr/api/v1/
webapp_rod_enabled: 'true'
webapp_sidekiq_disabled: 'false'
webapp_use_https: 'true'

############
# nfs
nfs_file_system: 10.66.73.40:/MA_25892_anah_demat/prod
has_nfs: true
