---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: redis-master
      image: debian
      image_version: jessie
      ansible_groups:
        - redis-master
    - name: redis-slave
      image: debian
      image_version: jessie
      ansible_groups:
        - redis-slave
verifier:
  name: serverspec
