FROM ruby:2.3.1

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y curl && apt-get install -y libicu-dev && apt-get install -y libpq-dev && apt-get install -y nodejs build-essential qt5-default libqt5webkit5-dev
RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \curl -sSL https://get.rvm.io | bash && /usr/local/rvm/bin/rvm install ruby-2.3.1
ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/rubies/ruby-2.3.1/bin/
RUN gem install bundler && gem install foreman && gem install rb-readline

VOLUME /app
WORKDIR /app

ENTRYPOINT tar jxvf app.tar.bz2 && foreman start



# need a config/database.yml
