---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: repos
      image: debian
      image_version: jessie
      ansible_groups:
        - repos
verifier:
  name: serverspec
